name: chat_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2
  firebase_storage: ^11.7.4
  google_sign_in: ^6.2.1
  fluttertoast: ^8.0.8
  image_picker: ^1.1.1
  shared_preferences: ^2.0.13
  intl: ^0.19.0
  photo_view: ^0.15.0
  provider: ^6.0.2
  country_code_picker: ^3.0.0
  url_launcher: ^6.0.20
  equatable: ^2.0.3
  google_sign_in_web: ^0.12.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
